### ISSUE TITLE
ERROR in : Can't resolve all parameters

### ISSUE THREAD

**Issue by pankajhartron** [kalyan11021980/angular-ssr-starter#1]
I followed your youtube tutorial and I am getting the following error on npm run start-frontend command.

Here frontend is the name of my project.

ERROR in : Can't resolve all parameters for HomeComponent in /home/panku/projects/learnmall/client/src/app/components/home/home.component.ts: ([object Object], ?).
src/app/components/home/home.component.ts(3,31): error TS2307: Cannot find module 'src/app/services/navbar.service'.
src/app/components/authentication/authentication.component.ts(6,31): error TS2307: Cannot find module 'src/app/services/navbar.service'.
src/app/components/dashboard/dashboard.component.ts(3,32): error TS2307: Cannot find module 'src/app/services/profile.service'.
src/app/components/dashboard/dashboard.component.ts(4,31): error TS2307: Cannot find module 'src/app/services/navbar.service'.
src/app/components/dashboard/dashboard.component.ts(6,27): error TS2307: Cannot find module 'src/app/classes/profile'.
src/app/components/dashboard/dashboard.component.ts(7,36): error TS2307: Cannot find module 'src/app/services/common-event.service'.
src/app/components/createcourse/createcourse.component.ts(2,31): error TS2307: Cannot find module 'src/app/services/navbar.service'.
src/app/components/createcourse/createcourse.component.ts(3,36): error TS2307: Cannot find module 'src/app/services/common-event.service'.
src/app/components/createcourse/createcourse.component.ts(6,46): error TS2307: Cannot find module 'src/app/classes/profile'.
src/app/components/linkedinauth/linkedinauth.component.ts(3,39): error TS2307: Cannot find module 'src/app/services/authentication.service'.
src/app/components/faq/faq.component.ts(2,31): error TS2307: Cannot find module 'src/app/services/navbar.service'.
src/app/components/my-profile/my-profile.component.ts(2,31): error TS2307: Cannot find module 'src/app/services/navbar.service'.
src/app/components/my-profile/my-profile.component.ts(4,92): error TS2307: Cannot find module 'src/app/classes/profile'.
src/app/components/my-profile/my-profile.component.ts(7,39): error TS2307: Cannot find module 'src/app/services/authentication.service'.
src/app/components/my-profile/my-profile.component.ts(8,37): error TS2307: Cannot find module 'src/app/services/create-course.service'.
src/app/components/my-profile/my-profile.component.ts(9,35): error TS2307: Cannot find module 'src/app/services/fileupload.service'.
src/app/components/my-profile/my-profile.component.ts(10,39): error TS2307: Cannot find module 'src/app/services/profile-details.service'.
src/app/components/pu-course/pu-course.component.ts(3,31): error TS2307: Cannot find module 'src/app/classes/coursedetails'.
src/app/components/pu-course/pu-course.component.ts(4,36): error TS2307: Cannot find module 'src/app/services/common-event.service'.
src/app/components/pu-course/pu-course.component.ts(5,37): error TS2307: Cannot find module 'src/app/services/create-course.service'.
src/app/components/pu-course/pu-course.component.ts(6,39): error TS2307: Cannot find module 'src/app/classes/profile'.
src/app/components/pu-course/pu-course.component.ts(8,31): error TS2307: Cannot find module 'src/app/services/navbar.service'.
src/app/components/news/news.component.ts(2,31): error TS2307: Cannot find module 'src/app/services/navbar.service'.
src/app/components/team/team.component.ts(2,31): error TS2307: Cannot find module 'src/app/services/navbar.service'.
src/app/components/all-courses/all-courses.component.ts(2,36): error TS2307: Cannot find module 'src/app/services/common-event.service'.
src/app/components/privacy-policy/privacy-policy.component.ts(2,31): error TS2307: Cannot find module 'src/app/services/navbar.service'.
src/app/components/referral/referral.component.ts(3,32): error TS2307: Cannot find module 'src/app/services/profile.service'.
src/app/app.component.ts(3,31): error TS2307: Cannot find module 'src/app/services/navbar.service'.
src/app/components/navbar/navbar.component.ts(4,31): error TS2307: Cannot find module 'src/app/services/navbar.service'.
src/app/components/add-course-videos/add-course-videos.component.ts(2,31): error TS2307: Cannot find module 'src/app/classes/coursedetails'.
src/app/components/add-course-videos/add-course-videos.component.ts(4,37): error TS2307: Cannot find module 'src/app/services/create-course.service'.
src/app/components/add-course-videos/add-course-videos.component.ts(5,35): error TS2307: Cannot find module 'src/app/services/fileupload.service'.
src/app/components/add-course-videos/add-course-videos.component.ts(6,36): error TS2307: Cannot find module 'src/app/services/common-event.service'.
src/app/components/profile-form/profile-form.component.ts(11,8): error TS2307: Cannot find module 'src/app/classes/profile'.
src/app/components/profile-form/profile-form.component.ts(20,39): error TS2307: Cannot find module 'src/app/services/authentication.service'.
src/app/components/profile-form/profile-form.component.ts(21,37): error TS2307: Cannot find module 'src/app/services/create-course.service'.
src/app/components/profile-form/profile-form.component.ts(22,35): error TS2307: Cannot find module 'src/app/services/fileupload.service'.
src/app/components/profile-form/profile-form.component.ts(23,39): error TS2307: Cannot find module 'src/app/services/profile-details.service'.
src/app/components/profile-form/profile-form.component.ts(24,36): error TS2307: Cannot find module 'src/app/services/common-event.service'.
src/app/components/course-preview/course-preview.component.ts(2,36): error TS2307: Cannot find module 'src/app/services/common-event.service'.
src/app/components/course-preview/course-preview.component.ts(3,37): error TS2307: Cannot find module 'src/app/services/create-course.service'.
src/app/components/course-preview/course-preview.component.ts(4,31): error TS2307: Cannot find module 'src/app/classes/coursedetails'.
src/app/components/course-preview/course-preview.component.ts(5,55): error TS2307: Cannot find module 'src/app/classes/profile'.
src/app/components/published/published.component.ts(2,37): error TS2307: Cannot find module 'src/app/services/create-course.service'.
src/app/components/unpublished/unpublished.component.ts(2,37): error TS2307: Cannot find module 'src/app/services/create-course.service'.

**Comment by pankajhartron** [comment]
@kalyan11021980 Urgent help needed

**Comment by kalyan11021980** [comment]
The following error coming as it's not able to find the modules. Have you checked your main module file for all these imports are correct. It's nothing to do with SSR. it's normal angulr error coming from wrong code. You can try fixing this issue by running ng serve as well

**Comment by pankajhartron** [comment]
Yeah, I have checked all the modules. ng build --prod is running perfectly. Also, before SSR everything was working fine. I implemented this on a live website.

**Comment by kalyan11021980** [comment]
Can you upload this in a repo and share me?

**Comment by pankajhartron** [comment]
It's my company's project. I am afraid I can't do that. Can you solve this some other way? That would be a great help.

**Comment by pankajhartron** [comment]
Hello sir, I am still stuck on this issue. Please help. You can charge me if you want. @kalyan11021980

**Comment by kalyan11021980** [comment]
I would suggest create a dummy project and replicate this issue and upload in git and share me url not your company project. Please understand without a project helping is difficult. I am ready to help you without any charge.

**Comment by pankajhartron** [comment]
Will the gitlab project link work?

**Comment by kalyan11021980** [comment]
Sure. As long as I can clone is fine

**Comment by kalyan11021980** [comment]
Closing the issue as there is no communication....
